### ISSUE TITLE
I get error with net_error++

### ISSUE THREAD

**Issue by TuznaSova150** [ottacom/m5stickc-coingecko-ticker#1]
Here is it the error i get can you please help me?
Arduino: 1.8.15 (Windows 10), Board: "ESP32 Pico Kit, Default, 921600, None"

C:\Users\User\Documents\Arduino\ETH.ticker\ETH.ticker.ino: In function 'void loop()':

ETH.ticker:55:11: error: 'net_error' was not declared in this scope

           net_error++;

           ^

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\User\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi

 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

'net_error' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ottacom** [comment]
I'm sorry for my delay, I couldn't see your Issue.
The code has bee updated , I pushed  a wrong version probably.
But now it's working!
Thanks
